name: Repack Boot Image via URL

on:
  workflow_dispatch:
    inputs:
      boot_img_url:
        description: 'URL of original boot.img'
        required: true
        default: 'https://example.com/path/to/boot.img'
      kernel_img_url:
        description: 'URL of new kernel Image'
        required: true
        default: 'https://example.com/path/to/Image'

jobs:
  repack_boot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 更新到v4版本

      - name: Setup Workspace
        run: |
          mkdir -p ${{ github.workspace }}/downloads
          mkdir -p ${{ github.workspace }}/output

      - name: Download Magisk
        run: |
          wget -q https://objects.githubusercontent.com/github-production-release-asset-2e65be/67702184/005b3804-00df-43f8-87af-1c8fba10554b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250518%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250518T155551Z&X-Amz-Expires=300&X-Amz-Signature=f35281719f9c5e1d625b4998f561543f4e5c4e084935f275e9856fbb5ac8052b&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3DMagisk-v29.0.apk&response-content-type=application%2Fvnd.android.package-archive
          ls -lh magisk.apk

      - name: Extract magiskboot
        run: |
          unzip -j magisk.apk 'lib/x86_64/libmagiskboot.so' -d .
          mv libmagiskboot.so magiskboot
          chmod +x magiskboot
          ./magiskboot --version

      - name: Download Boot Image
        run: |
          wget -O ${{ github.workspace }}/downloads/boot.img "${{ github.event.inputs.boot_img_url }}"
          file ${{ github.workspace }}/downloads/boot.img

      - name: Download Kernel Image
        run: |
          wget -O ${{ github.workspace }}/downloads/Image "${{ github.event.inputs.kernel_img_url }}"
          file ${{ github.workspace }}/downloads/Image

      - name: Unpack Boot Image
        run: |
          ./magiskboot unpack ${{ github.workspace }}/downloads/boot.img
          ls -l split_img/

      - name: Replace Kernel
        run: |
          cp -v ${{ github.workspace }}/downloads/Image split_img/kernel
          md5sum split_img/kernel

      - name: Repack Boot Image
        run: |
          ./magiskboot repack ${{ github.workspace }}/downloads/boot.img
          mv -v new-boot.img ${{ github.workspace }}/output/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom_boot_image
          path: ${{ github.workspace }}/output/new-boot.img