name: CI

on:
  push:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip

      - name: Clone and generate patch
        run: |
          git clone https://github.com/ferstar/xiaomi_xaga_kernel --filter=blob:none
          cd xiaomi_xaga_kernel
          git format-patch -1 aa2165cbb8e235becd5e3f2696b1d878b5e29010 -o ./patches/ 
          mv patches $GITHUB_WORKSPACE/

      - name: Upload patch
        uses: actions/upload-artifact@v4
        with:
          name: kernel-patches
          path: ${{ github.workspace }}/patches