name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git curl zip

      - name: Generate patch
        run: |
          # 克隆目标仓库
          git clone https://github.com/ferstar/xiaomi_xaga_kernel
          cd xiaomi_xaga_kernel
          # 生成指定提交的补丁
          git format-patch -1 aa2165cbb8e235becd5e3f2696b1d878b5e29010 -o ./patches/
          # 压缩补丁文件
          zip -r ../patches.zip ./patches/
          # 将补丁文件移动到工作目录根目录
          mv ../patches.zip $GITHUB_WORKSPACE/

      - name: Upload patch
        uses: actions/upload-artifact@v4
        with:
          name: patches
          path: ${{ github.workspace }}/patches.zip
