name: OPlus OOS Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2160

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        temp-reserve-mb: 2048
        swap-size-mb: 8192
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Configure Git
      run: |
         git config --global user.name "GitHub Actions"
         git config --global user.email "actions@github.com"

    - name: Clean up disk space
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet /etc/mysql /var/lib/mysql
        sudo rm -rf /usr/local/lib/android
        df -h

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 git curl zip

    - name: Install repo tool
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo

    - name: Initialize repo and sync
      run: |
        mkdir kernel_workspace && cd kernel_workspace
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/sm8550 -m oneplus_12r_v.xml --depth=1
        repo sync

    - name: Setup KernelSU
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
        cd ./KernelSU-Next/kernel
        sed -i 's/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=10200/' ./Makefile

    - name: clone susfs4ksu
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/kernel_platform
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android13-5.15
        git clone https://github.com/TheWildJames/kernel_patches.git


    - name: Add SUSFS
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common
        cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
        cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch ./
        cp ../susfs4ksu/kernel_patches/fs/* ./fs/
        cp ../susfs4ksu/kernel_patches/include/linux/* ./include/linux/
        cd ./KernelSU-Next/
        patch -p1 < 10_enable_susfs_for_ksu.patch || true
        

    - name: Apply patches
      run: | 
        cd $GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common
        patch -p1 < 50_add_susfs_in_gki-android13-5.15.patch || true
        cp ../kernel_patches/69_hide_stuff.patch ./
        patch -p1 -F 3 < 69_hide_stuff.patch || true
        cp ../kernel_patches/selinux.c_fix.patch ./
        patch -p1 -F 3 < selinux.c_fix.patch
        cp ../kernel_patches/core_hook.c_fix.patch ./
        patch -p1 --fuzz=3 < ./core_hook.c_fix.patch
        cp ../kernel_patches/apk_sign.c_fix.patch ./
        patch -p1 -F 3 < apk_sign.c_fix.patch

    - name: Build defconfig
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/kernel_platform/
        echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> ./common/arch/arm64/configs/gki_defconfigig
        cd ..
        sed -i '2s/check_defconfig//' ./kernel_platform/common/build.config.gki

    - name: Make working directory clean to avoid dirty
      run: |
        cd kernel_workspace/kernel_platform/common
        rm -rf android/abi_gki_protected_exports_*
        repo status

    - name: Build kernel
      run: |
        cd kernel_workspace
        LTO=thin ./kernel_platform/oplus/build/oplus_build_kernel.sh kalama gki

    - name: Make AnyKernel3
      run: |
        git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
        rm -rf ./AnyKernel3/.git
        cp kernel_workspace/kernel_platform/out/msm-kernel-kalama-gki/dist/Image ./AnyKernel3/

    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-OSS-OPace3-V
        path: ./AnyKernel3/*

    - name: Upload kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Image-OSS-OPace3-V
        path: kernel_workspace/kernel_platform/out/msm-kernel-kalama-gki/dist/Image

    - name: Upload boot.img
      uses: actions/upload-artifact@v4
      with:
        name: boot-OSS-OPace3-V.img
        path: kernel_workspace/kernel_platform/out/msm-kernel-kalama-gki/dist/boot.img
