# .github/workflows/build5pro.yml

name: Build 5pro (xmake)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

env:
  TZ: Asia/Shanghai
  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_COMPRESS: 1
  CCACHE_MAXSIZE: 10G

jobs:
  build:
    name: Build Kernel by ${{ github.actor }} (xmake)
    runs-on: ubuntu-latest
    env:
      CLANG_VERSION: Clang-19.0.0git-20240723
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: brokestar233/android_kernel_common_oneplus_sm8750
          ref: v8
          path: kernel_workspace/android-kernel
          
      - name: Checkout susfs4ksu
        uses: actions/checkout@v4
        with:
          repository: ShirkNeko/susfs4ksu
          ref: gki-android15-6.6
          path: kernel_workspace/susfs4ksu
          
      - name: Checkout SukiSU_patch
        uses: actions/checkout@v4
        with:
          repository: ShirkNeko/SukiSU_patch
          path: kernel_workspace/SukiSU_patch

      - name: Checkout sched_ext
        uses: actions/checkout@v4
        with:
          repository: HanKuCha/sched_ext
          path: kernel_workspace/sched_ext

      - name: Copy sched_ext
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          cp -r ./sched_ext/* ./android-kernel/kernel/sched

      - name: Set swap to 10G
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Setup build kernel environment
        run: |
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date '+%y%m%d')" >> $GITHUB_ENV
          sudo apt-get update
          sudo apt-get install -y git dwarves libelf-dev ccache automake flex bison build-essential \
                zlib1g-dev libncurses5-dev libc6-dev-i386 bc device-tree-compiler python3 make pahole \
                libssl-dev libffi-dev libxml2-dev libxslt1-dev libgmp-dev libmpfr-dev libmpc-dev \
                ninja-build python3-pip
          mkdir -p "${{ env.CCACHE_DIR }}"
          ccache --set-config=cache_dir=${{ env.CCACHE_DIR }}
          ccache --set-config=max_size=${{ env.CCACHE_MAXSIZE }}
          ccache --set-config=compression=true
          ccache --set-config=compression_level=1
          ccache --set-config=hash_dir=false
          ccache --set-config=sloppiness=file_macro,locale,time_macros
          ccache --show-config
          ccache -z

      - name: Configure Git for kernel build
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Setup build date
        id: date
        run: |
          current_date=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')
          echo "current-date=${current_date}" >> $GITHUB_OUTPUT

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ env.CLANG_VERSION }}-${{ hashFiles('**/Kbuild') }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ env.CLANG_VERSION }}-
            ccache-${{ runner.os }}-

      - name: Cache Clang toolchain
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/kernel_workspace/clang-aosp
          key: ${{ env.CLANG_VERSION }}

      - name: Download & extract Clang-aosp
        if: steps.cache-clang.outputs.cache-hit != 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          mkdir -p clang-aosp
          wget -O zyclang.tar.gz https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240723-release/Clang-19.0.0git-20240723.tar.gz
          tar -C clang-aosp -zxvf zyclang.tar.gz

      - name: Patch setlocalversion
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/scripts
          sed -i 's/ -dirty//g' setlocalversion
          sed -i 's/OKI/android15-8/g' setlocalversion

      - name: Setup KernelSU
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/susfs-main/kernel/setup.sh" | bash -s susfs-main
          KSU_VERSION=$(cd KernelSU && expr $(/usr/bin/git rev-list --count susfs-main) + 10700)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

      - name: Setup susfs
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          cp -r ../susfs4ksu/kernel_patches/fs/* ./fs/
          cp -r ../susfs4ksu/kernel_patches/include/linux/* ./include/linux/
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch ./
          cp ../SukiSU_patch/hooks/syscall_hooks.patch ./
          patch -p1 < 50_add_susfs_in_gki-android15-6.6.patch || true
          patch -p1 -F 3 < syscall_hooks.patch || true

      - name: Apply HMBird GKI patch
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/drivers
          cat << 'EOF' > hmbird_patch.c
          #include <linux/init.h>
          #include <linux/module.h>
          #include <linux/of.h>
          #include <linux/slab.h>
          #include <linux/string.h>
          #include <linux/printk.h>

          static int __init hmbird_patch_init(void)
          {
              struct device_node *ver_np;
              const char *type;
              int ret;

              ver_np = of_find_node_by_path("/soc/oplus,hmbird/version_type");
              if (!ver_np) {
                   pr_info("hmbird_patch: version_type node not found\n");
                   return 0;
              }

              ret = of_property_read_string(ver_np, "type", &type);
              if (ret) {
                   pr_info("hmbird_patch: type property not found\n");
                   of_node_put(ver_np);
                   return 0;
              }

              if (strcmp(type, "HMBIRD_OGKI") != 0) {
                   of_node_put(ver_np);
                   return 0;
              }

              struct property *prop = of_find_property(ver_np, "type", NULL);
              if (prop) {
                   struct property *new_prop = kzalloc(sizeof(*new_prop), GFP_KERNEL);
                   if (!new_prop) {
                        pr_err("hmbird_patch: kzalloc for new_prop failed\n");
                        of_node_put(ver_np);
                        return -ENOMEM;
                   }
                   new_prop->name = prop->name;
                   new_prop->length = strlen("HMBIRD_GKI") + 1;
                   new_prop->value = kzalloc(new_prop->length, GFP_KERNEL);
                   if (!new_prop->value) {
                        pr_err("hmbird_patch: kzalloc for new_prop->value failed\n");
                        kfree(new_prop);
                        of_node_put(ver_np);
                        return -ENOMEM;
                   }
                   strcpy(new_prop->value, "HMBIRD_GKI");

                   if (of_remove_property(ver_np, prop)) {
                        pr_err("hmbird_patch: of_remove_property failed\n");
                        kfree(new_prop->value);
                        kfree(new_prop);
                        of_node_put(ver_np);
                        return -EINVAL;
                   }
                   if (of_add_property(ver_np, new_prop)) {
                        pr_err("hmbird_patch: of_add_property failed\n");
                        kfree(new_prop->value);
                        kfree(new_prop);
                        of_node_put(ver_np);
                        return -EINVAL;
                   }
                   pr_info("hmbird_patch: success from HMBIRD_OGKI to HMBIRD_GKI\n");
              }
              else {
                  pr_info("hmbird_patch: type property structure not found\n");
              }
              of_node_put(ver_np);
              return 0;
          }
          early_initcall(hmbird_patch_init);
          MODULE_LICENSE("GPL");
          MODULE_AUTHOR("reigadegr");
          MODULE_DESCRIPTION("Forcefully convert HMBIRD_OGKI to HMBIRD_GKI.");
          EOF

          if ! grep -q "hmbird_patch.o" Makefile; then
            echo "obj-y += hmbird_patch.o" >> Makefile
          fi

      - name: Add SUSFS Configuration Settings
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          if [ ! -f "arch/arm64/configs/gki_defconfig" ]; then
              echo "错误: gki_defconfig 文件不存在！"
              ls -la arch/arm64/configs
              exit 1
          fi

          cat <<EOF >> arch/arm64/configs/gki_defconfig
          CONFIG_KSU=y
          CONFIG_KSU_SUSFS_SUS_SU=n
          CONFIG_KSU_MANUAL_HOOK=y
          CONFIG_KSU_SUSFS=y
          CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_PATH=y
          CONFIG_KSU_SUSFS_SUS_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_KSTAT=y
          CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n
          CONFIG_KSU_SUSFS_TRY_UMOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_SPOOF_UNAME=y
          CONFIG_KSU_SUSFS_ENABLE_LOG=y
          CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
          CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
          CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
          CONFIG_LTO=y
          CONFIG_THIN_ARCHIVES=y
          CONFIG_CRYPTO_LZ4K=n
          CONFIG_CRYPTO_LZ4KD=n
          CONFIG_CRYPTO_LZ4HC=n
          CONFIG_CRYPTO_842=n
          CONFIG_LOCALVERSION="-g013ec21bba94-abogki383916444-4k"
          EOF

      # 修复xmake安装和配置
      - name: Install xmake with full dependencies
        run: |
          # 确保安装完整版xmake
          curl -fsSL https://xmake.io/shget.text | bash -s -- --yes
          ~/.local/bin/xmake --version
          ~/.local/bin/xmake update -s dev
          
          # 添加xmake到PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build kernel with xmake
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          
          # 设置环境变量
          export PATH=$HOME/.local/bin:$PATH
          export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH
          export CCACHE_DIR=${{ env.CCACHE_DIR }}
          export ARCH=arm64
          export SUBARCH=arm64
          export HEADER_ARCH=arm64
          export KBUILD_BUILD_HOST=builder@localhost
          export LLVM=1
          export LLVM_IAS=1
          
          # 创建xmake配置
          cat > xmake.lua <<'EOL'
          target("kernel")
             set_kind("binary")
             set_arch("arm64")
             set_plat("linux")
             set_toolchains("clang")
             
             -- 添加编译标志
             add_cflags(
                 "-O2",
                 "-pipe",
                 "-fno-strict-aliasing",
                 "-fno-common",
                 "-fshort-wchar",
                 "-fno-PIE",
                 "-fno-asynchronous-unwind-tables",
                 "-fno-unwind-tables",
                 "-fno-delete-null-pointer-checks",
                 "-fmacro-prefix-map=./=",
                 "-fstack-protector-strong",
                 "-fno-allow-store-data-races",
                 "-fno-omit-frame-pointer",
                 "-fno-optimize-sibling-calls",
                 "-fno-var-tracking-assignments",
                 "-fno-strict-overflow",
                 "-fconserve-stack",
                 "-ffunction-sections",
                 "-fdata-sections",
                 "-fno-stack-check",
                 "-flto=thin",
                 "-fno-vectorize",
                 "-fno-unroll-loops",
                 "-fno-slp-vectorize"
             )
             
             -- 添加链接标志
             add_ldflags(
                 "-z noexecstack",
                 "-z relro",
                 "-z now",
                 "-z max-page-size=4096",
                 "--pack-dyn-relocs=relr",
                 "--use-android-relr-tags",
                 "--thinlto-cache-dir=" .. os.getenv("CCACHE_DIR") .. "/thinlto-cache"
             )
             
             -- 添加包含目录
             add_includedirs(
                 "include",
                 "arch/arm64/include",
                 "arch/arm64/include/generated"
             )
             
             -- 添加源文件
             add_files(
                 "arch/arm64/kernel/head.S",
                 "arch/arm64/kernel/**.S",
                 "arch/arm64/kernel/**.c",
                 "kernel/**.c",
                 "fs/**.c",
                 "drivers/**.c",
                 "mm/**.c",
                 "net/**.c",
                 "ipc/**.c",
                 "security/**.c",
                 "init/**.c",
                 "lib/**.c",
                 "crypto/**.c",
                 "block/**.c"
             )
             
             -- 构建前生成配置
             before_build(function (target)
                 os.exec("make gki_defconfig")
             end)
             
             -- 构建后复制镜像
             after_build(function (target)
                 os.mkdir("out/arch/arm64/boot")
                 os.cp("build/linux/arm64/release/Image", "out/arch/arm64/boot/Image")
             end)
          EOL
          
          # 创建thinlto缓存目录
          mkdir -p "$CCACHE_DIR/thinlto-cache"
          
          # 使用xmake构建
          xmake f -p linux -a arm64 --toolchain=clang -c
          xmake build -j$(nproc) kernel
          
          # 显示ccache统计
          ccache -s

      - name: Check kernel output files
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          if [ -f android-kernel/out/arch/arm64/boot/Image ]; then
              echo "CHECK_IMAGE=true" >> $GITHUB_ENV
          else
              echo "Kernel output file is empty"
              echo "===== out/arch/arm64/boot 目录内容 ====="
              ls -la android-kernel/out/arch/arm64/boot
              exit 1
          fi

      - name: Make Anykernel3
        if: env.CHECK_IMAGE == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
          rm -rf AnyKernel3/.git
          cp android-kernel/out/arch/arm64/boot/Image AnyKernel3/
          cd AnyKernel3
          zip -r9 ../AnyKernel3-${{ env.KSUVER }}.zip *
          mv ../AnyKernel3-${{ env.KSUVER }}.zip $GITHUB_WORKSPACE/

      - name: Upload Image
        if: env.CHECK_IMAGE == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Image-${{ env.KSUVER }}
          path: kernel_workspace/android-kernel/out/arch/arm64/boot/Image

      - name: Upload AnyKernel3
        if: env.CHECK_IMAGE == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3-${{ env.KSUVER }}
          path: ${{ github.workspace }}/AnyKernel3-${{ env.KSUVER }}.zip

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.KSUVER }}
          name: "sukisu ${{ env.KSUVER }}"
          draft: false
          prerelease: ${{ contains(github.ref_name, 'rc') }}
          generate_release_notes: true
          body: |
            **Build Details**
            - KernelSU Version: ${{ env.KSUVER }}
            - Build Date: ${{ steps.date.outputs.current-date }}
            **Build Environment:**
            - OS: ubuntu-latest
            - Clang Version: ${{ env.CLANG_VERSION }}
            - Build System: xmake
          files: |
            AnyKernel3-${{ env.KSUVER }}.zip
            kernel_workspace/android-kernel/out/arch/arm64/boot/Image